# This file is NOT reloaded automatically when you use 'bundle exec jekyll
# serve'. If you change this file, restart the server.


# ===== SITE SETTINGS =====
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, etc.
# Liquid tags.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Logz.io Documentation Portal
description: >- # this means to ignore newlines until "baseurl:"
  Parse, visualize, set up alerts & leverage AI with cloud-based ELK. Free Trial!
  AWS Integration · Long-term Data Retention · Essential DevOps Tool · Multi-role Definitions
  Services: Log Analytics, DevOps Automation, Critical Event Prediction
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://affectionate-mccarthy-d5aefa.netlify.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: logzio
github_username:  logzio

# if you wish to integrate disqus on pages set your shortname here
disqus:
  shortname: 'sboroda'
  site_url: 'imnotashrimp.github.com'

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-117595536-1'

# ===== COLLECTIONS =====
# Collections are the highest-level categories of Logz.io content.

collections_dir: logzio_collections # all collections are contained in this directory

collections:
  getting-started:
    output: true
  ship-and-parse-logs:
    output: true
  monitor-logs:
    output: true
  account-settings:
    output: true
  # integrations:
    # output: true
  developer-center:
   output: true
  troubleshooting:
    output: true


# ===== BUILD SETTINGS =====
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


kramdown:
  # auto_ids: true

# These items will not be processed, by default. Add new items as array entries.
exclude:
  - .DS_Store


# ===== SOURCE AND DESTINATION =====
# Don't mess with these, unless you're willing to move a lot of files around.
source: ./_source
destination: ./_site

# ===== BREADCRUMBS =====
breadcrumbs:
  root:
    hide: true  # show breadcrumbs on root/home page
    image: true # Show image or title text

# ===== SEARCH =====
algolia:
  application_id: 5JG6L7AEGE
  index_name:     logzio_docs
  search_only_api_key: 0ee9dbc788039985af9620e6570bbc34
